version: "3.8"

services:
  hello-world-microservice:
    image: hello-world-microservice
    build:
      context: apps/hello-world-microservice
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    network_mode: host

  api-gateway:
    image: api-gateway
    build:
      context: api-gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - hello-world-microservice
    network_mode: host
