version: "3"

services:
  hello-world-microservice:
    build:
      context: ./apps/hello-world-microservice
      dockerfile: ./Dockerfile
    ports:
      - "3001:3001"

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
