version: "3.8"

services:
  hello-world-microservice:
    build: apps/hello-world-microservice
    ports:
      - "3001:3001"
    network_mode: host

  api-gateway:
    build: api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - hello-world-microservice
    network_mode: host
