version: "3.9"

services:
  hello-world-microservice:
    build:
      context: ./apps/hello-world-microservice
      dockerfile: ./Dockerfile
    expose:
      - "3001"
    networks:
      - my-network
    environment:
      - MICROSERVICE_HOST=hello-world-microservice

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - hello-world-microservice
    networks:
      - my-network
    environment:
      - MICROSERVICE_HOST=hello-world-microservice

networks:
  my-network:
    driver: bridge
