name: Build and Deploy Node.js app to Azure Container Registry

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
          login-server: helloworldadammehdaoui.azurecr.io
          username: helloworldadammehdaoui
          password: PnRpM54cPkVLABCTQ2b12uPKJQE3bqbcTvTeNLp+UL+ACRDp+3r0
      - run: |
          cd api-gateway
          docker build . -t helloworldadammehdaoui.azurecr.io/api-gateway:${{ github.sha }}
          docker push helloworldadammehdaoui.azurecr.io/api-gateway:${{ github.sha }}
      - run: |
          cd apps/hello-world-microservice
          docker build . -t helloworldadammehdaoui.azurecr.io/hello-world-microservice:${{ github.sha }}
          docker push helloworldadammehdaoui.azurecr.io/hello-world-microservice:${{ github.sha }}
